spring.application.name=PostService

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/post_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:6c2b8f8e9a4d7f1e3b5c8a2d4f6e8a1c3b5d7f9e2a4c6b8d1f3e5a7c9b2d4f6e8a1c}
jwt.expiration=86400000